import type { ThemePreset, Theme, PrimitiveTokens, SemanticTokens } from "../types/theme";

const lightPrimitives: PrimitiveTokens = {
  color: {
    primary: "#4B39EF",
    secondary: "#39D2C0",
    tertiary: "#F9CF58",
    error: "#FF5963",
    success: "#249689",
    warning: "#F9CF58",
    background: "#F1F4F8",
    surface: "#FFFFFF",
    "surface-elevated": "#FFFFFF",
    border: "#E1E4E8",
    "border-hover": "#C5C9CD",
    "text-primary": "#14181B",
    "text-secondary": "#57636C",
    "text-muted": "#8B939C",
    "text-inverse": "#FFFFFF",
    "accent": "#4B39EF",
    "accent-hover": "#3D2FB8",
    "accent-subtle": "#EEECFF",
  },
  spacing: {
    "0": "0px",
    "0.5": "0.125rem",
    "1": "0.25rem",
    "2": "0.5rem",
    "3": "0.75rem",
    "4": "1rem",
    "5": "1.25rem",
    "6": "1.5rem",
    "8": "2rem",
    "10": "2.5rem",
    "12": "3rem",
    "16": "4rem",
    "20": "5rem",
    "24": "6rem",
  },
  radius: {
    none: "0px",
    sm: "0.125rem",
    md: "0.375rem",
    lg: "0.5rem",
    xl: "0.75rem",
    "2xl": "1rem",
    full: "9999px",
  },
  shadow: {
    none: "none",
    sm: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
    md: "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)",
    lg: "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)",
    xl: "0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)",
  },
  font: {
    sans: "ui-sans-serif, system-ui, sans-serif",
    serif: "ui-serif, Georgia, serif",
    mono: "ui-monospace, SFMono-Regular, monospace",
  },
  border: {
    "width-0": "0px",
    "width-thin": "1px",
    "width-medium": "2px",
    "width-thick": "4px",
    "style-solid": "solid",
    "style-dashed": "dashed",
    "style-dotted": "dotted",
    "style-none": "none",
  },
};

const lightSemantics: SemanticTokens = {
  color: {
    "bg-primary": "{primitives.color.primary}",
    "bg-secondary": "{primitives.color.secondary}",
    "bg-success": "{primitives.color.success}",
    "bg-error": "{primitives.color.error}",
    "bg-warning": "{primitives.color.warning}",
    "bg-background": "{primitives.color.background}",
    "bg-surface": "{primitives.color.surface}",
    "bg-surface-elevated": "{primitives.color.surface-elevated}",
    "bg-border": "{primitives.color.border}",
    "text-primary": "{primitives.color.text-primary}",
    "text-secondary": "{primitives.color.text-secondary}",
    "text-muted": "{primitives.color.text-muted}",
    "text-inverse": "{primitives.color.text-inverse}",
    "text-on-primary": "{primitives.color.text-inverse}",
    "border-default": "{primitives.color.border}",
    "border-hover": "{primitives.color.border-hover}",
  },
  spacing: {
    xs: "{primitives.spacing.1}",
    sm: "{primitives.spacing.2}",
    md: "{primitives.spacing.4}",
    lg: "{primitives.spacing.6}",
    xl: "{primitives.spacing.8}",
    "2xl": "{primitives.spacing.12}",
  },
  radius: {
    sm: "{primitives.radius.sm}",
    md: "{primitives.radius.md}",
    lg: "{primitives.radius.lg}",
    xl: "{primitives.radius.xl}",
    full: "{primitives.radius.full}",
  },
  shadow: {
    sm: "{primitives.shadow.sm}",
    md: "{primitives.shadow.md}",
    lg: "{primitives.shadow.lg}",
    xl: "{primitives.shadow.xl}",
  },
  typography: {
    "display-large": {
      fontFamily: "{primitives.font.sans}",
      fontSize: "text-4xl",
      fontWeight: 700,
      lineHeight: "leading-tight",
      letterSpacing: "tracking-tight",
    },
    "headline-medium": {
      fontFamily: "{primitives.font.sans}",
      fontSize: "text-2xl",
      fontWeight: 600,
      lineHeight: "leading-snug",
      letterSpacing: "tracking-tight",
    },
    "headline-small": {
      fontFamily: "{primitives.font.sans}",
      fontSize: "text-xl",
      fontWeight: 600,
      lineHeight: "leading-snug",
      letterSpacing: "tracking-tight",
    },
    "title-large": {
      fontFamily: "{primitives.font.sans}",
      fontSize: "text-lg",
      fontWeight: 600,
      lineHeight: "leading-snug",
      letterSpacing: "tracking-normal",
    },
    "title-medium": {
      fontFamily: "{primitives.font.sans}",
      fontSize: "text-base",
      fontWeight: 600,
      lineHeight: "leading-normal",
      letterSpacing: "tracking-normal",
    },
    "body-large": {
      fontFamily: "{primitives.font.sans}",
      fontSize: "text-base",
      fontWeight: 400,
      lineHeight: "leading-relaxed",
      letterSpacing: "tracking-normal",
    },
    "body-medium": {
      fontFamily: "{primitives.font.sans}",
      fontSize: "text-sm",
      fontWeight: 400,
      lineHeight: "leading-normal",
      letterSpacing: "tracking-normal",
    },
    "label-large": {
      fontFamily: "{primitives.font.sans}",
      fontSize: "text-sm",
      fontWeight: 500,
      lineHeight: "leading-normal",
      letterSpacing: "tracking-wide",
    },
    "label-medium": {
      fontFamily: "{primitives.font.sans}",
      fontSize: "text-xs",
      fontWeight: 500,
      lineHeight: "leading-normal",
      letterSpacing: "tracking-wide",
    },
  },
};

export const defaultLightTheme: Theme = {
  id: "theme-light",
  name: "Light",
  mode: "light",
  breakpoints: {
    sm: "640px",
    md: "768px",
    lg: "1024px",
    xl: "1280px",
    "2xl": "1536px",
  },
  primitives: lightPrimitives,
  semantics: lightSemantics,
  variants: {
    button: [
      {
        name: "primary",
        props: { variant: "primary" },
        style: {
          background: "{primitives.color.primary}",
          color: "{primitives.color.text-inverse}",
          padding: "px-4 py-2",
          borderRadius: "{primitives.radius.md}",
          fontWeight: 500,
        },
      },
      {
        name: "secondary",
        props: { variant: "secondary" },
        style: {
          background: "transparent",
          color: "{primitives.color.primary}",
          padding: "px-4 py-2",
          borderRadius: "{primitives.radius.md}",
          borderWidth: "{primitives.border.width.thin}",
          borderColor: "{primitives.color.border}",
          fontWeight: 500,
        },
      },
      {
        name: "ghost",
        props: { variant: "ghost" },
        style: {
          background: "transparent",
          color: "{primitives.color.text-secondary}",
          padding: "px-4 py-2",
          borderRadius: "{primitives.radius.md}",
          fontWeight: 500,
        },
      },
      {
        name: "danger",
        props: { variant: "danger" },
        style: {
          background: "{primitives.color.error}",
          color: "{primitives.color.text-inverse}",
          padding: "px-4 py-2",
          borderRadius: "{primitives.radius.md}",
          fontWeight: 500,
        },
      },
    ],
    card: [
      {
        name: "elevated",
        props: { variant: "elevated" },
        style: {
          background: "{primitives.color.surface}",
          padding: "p-6",
          borderRadius: "{primitives.radius.lg}",
          shadow: "{primitives.shadow.md}",
          borderWidth: "{primitives.border.width.thin}",
          borderColor: "{primitives.color.border}",
        },
      },
      {
        name: "outlined",
        props: { variant: "outlined" },
        style: {
          background: "transparent",
          padding: "p-6",
          borderRadius: "{primitives.radius.lg}",
          borderWidth: "{primitives.border.width.thin}",
          borderColor: "{primitives.color.border}",
        },
      },
    ],
    textfield: [
      {
        name: "default",
        props: { variant: "default" },
        style: {
          padding: "px-3 py-2",
          borderRadius: "{primitives.radius.md}",
          borderWidth: "{primitives.border.width.thin}",
          borderColor: "{primitives.color.border}",
          background: "{primitives.color.surface}",
        },
      },
      {
        name: "filled",
        props: { variant: "filled" },
        style: {
          padding: "px-3 py-2",
          borderRadius: "{primitives.radius.md}",
          background: "{primitives.color.background}",
          borderWidth: "{primitives.border.width.0}",
        },
      },
    ],
    badge: [
      {
        name: "solid",
        props: { variant: "solid" },
        style: {
          background: "{primitives.color.primary}",
          color: "{primitives.color.text-inverse}",
          padding: "px-2 py-0.5",
          borderRadius: "{primitives.radius.full}",
          fontSize: "text-xs",
          fontWeight: 500,
        },
      },
      {
        name: "subtle",
        props: { variant: "subtle" },
        style: {
          background: "{primitives.color.accent-subtle}",
          color: "{primitives.color.primary}",
          padding: "px-2 py-0.5",
          borderRadius: "{primitives.radius.full}",
          fontSize: "text-xs",
          fontWeight: 500,
        },
      },
    ],
  },
};

const darkPrimitives: PrimitiveTokens = {
  ...lightPrimitives,
  color: {
    primary: "#8B7DFA",
    secondary: "#5CE1D4",
    tertiary: "#F9CF58",
    error: "#FF6B73",
    success: "#3DB8A8",
    warning: "#F9CF58",
    background: "#0B0F14",
    surface: "#151B23",
    "surface-elevated": "#1C2430",
    border: "#2A3441",
    "border-hover": "#3A4858",
    "text-primary": "#F9FAFB",
    "text-secondary": "#A3AEB8",
    "text-muted": "#6B7885",
    "text-inverse": "#0B0F14",
    accent: "#8B7DFA",
    "accent-hover": "#A598FB",
    "accent-subtle": "#1E2540",
  },
};

const darkSemantics: SemanticTokens = {
  ...lightSemantics,
  color: {
    ...lightSemantics.color,
    "bg-background": "{primitives.color.background}",
    "bg-surface": "{primitives.color.surface}",
    "bg-surface-elevated": "{primitives.color.surface-elevated}",
    "bg-border": "{primitives.color.border}",
    "text-primary": "{primitives.color.text-primary}",
    "text-secondary": "{primitives.color.text-secondary}",
    "text-muted": "{primitives.color.text-muted}",
    "text-inverse": "{primitives.color.text-inverse}",
    "text-on-primary": "{primitives.color.text-inverse}",
    "border-default": "{primitives.color.border}",
    "border-hover": "{primitives.color.border-hover}",
  },
};

export const defaultDarkTheme: Theme = {
  ...defaultLightTheme,
  id: "theme-dark",
  name: "Dark",
  mode: "dark",
  primitives: darkPrimitives,
  semantics: darkSemantics,
};

export const defaultLightPreset: ThemePreset = {
  id: "preset-light",
  label: "Light",
  mode: "light",
  theme: defaultLightTheme,
};

export const defaultDarkPreset: ThemePreset = {
  id: "preset-dark",
  label: "Dark",
  mode: "dark",
  theme: defaultDarkTheme,
};
