/**
 * Declarative DoctypeMeta definitions for all 11 Industry Consoles.
 *
 * Provides schemas, fields, list views, filters, and state machine transitions
 * for all primary transactional entities across the industry verticals.
 */

import type { DoctypeMeta } from "../../domain/doctypes/types";

// 1. School ABC (school-abc)
export const TUITION_FEE_META: DoctypeMeta = {
  name: "TuitionFee",
  label: { id: "Tagihan SPP Siswa", en: "Student Tuition Fee" },
  module: "Keuangan & Siswa",
  naming: "SPP-.YYYY.-.#####",
  titleField: "studentName",
  fields: [
    { key: "id", label: { id: "Nomor Tagihan", en: "Invoice No" }, widget: "TextField", readOnly: true },
    { key: "companyId", label: { id: "Perusahaan", en: "Company" }, widget: "TextField", readOnly: true },
    { key: "studentName", label: { id: "Nama Siswa", en: "Student Name" }, widget: "TextField", required: true, section: "Data Siswa" },
    { key: "studentId", label: { id: "NIS", en: "Student ID" }, widget: "TextField", required: true, section: "Data Siswa" },
    { key: "grade", label: { id: "Kelas", en: "Class / Grade" }, widget: "TextField", required: true, section: "Data Siswa" },
    { key: "month", label: { id: "Bulan Periode", en: "Period Month" }, widget: "TextField", section: "Informasi Tagihan" },
    { key: "date", label: { id: "Tanggal Tagihan", en: "Invoice Date" }, widget: "Date", section: "Informasi Tagihan" },
    { key: "dueDate", label: { id: "Jatuh Tempo", en: "Due Date" }, widget: "Date", section: "Informasi Tagihan" },
    { key: "total", label: { id: "Nominal SPP", en: "Tuition Amount" }, widget: "Currency", required: true, section: "Finansial" },
    { key: "paidAmount", label: { id: "Sudah Dibayar", en: "Paid Amount" }, widget: "Currency", section: "Finansial" },
    { key: "outstandingAmount", label: { id: "Sisa Tagihan", en: "Outstanding Amount" }, widget: "Currency", section: "Finansial" },
    { key: "batchId", label: { id: "Batch SPP", en: "Fee Batch" }, widget: "TextField", section: "Informasi Tagihan" },
    { key: "paymentId", label: { id: "No. Pembayaran", en: "Payment ID" }, widget: "TextField", section: "Finansial" },
    { key: "dunningCount", label: { id: "Jumlah Reminder", en: "Dunning Count" }, widget: "TextField", section: "Kontrol" },
    {
      key: "status",
      label: { id: "Status Pembayaran", en: "Payment Status" },
      widget: "Select",
      section: "Finansial",
      options: [
        { value: "Belum Bayar", label: "Belum Bayar" },
        { value: "Jatuh Tempo", label: "Jatuh Tempo" },
        { value: "Lunas", label: "Lunas" },
        { value: "Batal", label: "Batal" },
      ],
    },
  ],
  listView: {
    columns: [
      { field: "id", width: "w-36" },
      { field: "studentName" },
      { field: "grade" },
      { field: "month" },
      { field: "total", align: "right" },
      { field: "outstandingAmount", align: "right" },
      { field: "status", align: "center" },
    ],
    filters: [
      {
        field: "status",
        label: { id: "Status", en: "Status" },
        widget: "Select",
        options: [
          { value: "Belum Bayar", label: "Belum Bayar" },
          { value: "Jatuh Tempo", label: "Jatuh Tempo" },
          { value: "Lunas", label: "Lunas" },
        ],
      },
    ],
    defaultSort: { field: "date", dir: "desc" },
    pageSize: 15,
    statusField: "status",
  },
  states: {
    field: "status",
    values: ["Belum Bayar", "Jatuh Tempo", "Lunas", "Batal"],
    initial: "Belum Bayar",
    transitions: [
      { name: "pay", label: { id: "Terima Pembayaran", en: "Receive Payment" }, from: ["Belum Bayar", "Jatuh Tempo"], to: "Lunas", posting: true },
      { name: "cancel", label: { id: "Batalkan Tagihan", en: "Cancel Fee" }, from: ["Belum Bayar"], to: "Batal" },
    ],
  },
  permissions: {
    "System Manager": { read: true, write: true, submit: true, delete: true },
    "Accounts User": { read: true, write: true, submit: true, delete: false },
  },
};

// 2. Factory ABC (factory-abc)
export const WORK_ORDER_META: DoctypeMeta = {
  name: "WorkOrder",
  label: { id: "Perintah Kerja Produksi (WO)", en: "Work Order (WO)" },
  module: "Manufaktur & MRP",
  naming: "WO-.YYYY.-.#####",
  titleField: "productName",
  fields: [
    { key: "id", label: { id: "Nomor SPK / WO", en: "Work Order No" }, widget: "TextField", readOnly: true },
    { key: "companyId", label: { id: "Perusahaan", en: "Company" }, widget: "TextField", readOnly: true },
    { key: "productName", label: { id: "Produk Jadi", en: "Finished Product" }, widget: "TextField", required: true, section: "Detail Produksi" },
    { key: "bomCode", label: { id: "Kode BOM", en: "BOM Code" }, widget: "TextField", required: true, section: "Detail Produksi" },
    { key: "targetQty", label: { id: "Target Produksi", en: "Target Qty" }, widget: "TextField", default: 100, section: "Kuantitas" },
    { key: "completedQty", label: { id: "Selesai Dibuat", en: "Completed Qty" }, widget: "TextField", default: 0, section: "Kuantitas" },
    { key: "rejectedQty", label: { id: "Reject QC", en: "QC Reject Qty" }, widget: "TextField", default: 0, section: "Kuantitas" },
    { key: "workstation", label: { id: "Stasiun Kerja / Mesin", en: "Workstation" }, widget: "TextField", section: "Jadwal" },
    { key: "startDate", label: { id: "Tanggal Mulai", en: "Start Date" }, widget: "Date", section: "Jadwal" },
    { key: "plannedCost", label: { id: "Biaya Rencana", en: "Planned Cost" }, widget: "Currency", section: "Biaya" },
    { key: "actualCost", label: { id: "Biaya Aktual", en: "Actual Cost" }, widget: "Currency", section: "Biaya" },
    { key: "actualMaterialCost", label: { id: "Material Aktual", en: "Actual Material Cost" }, widget: "Currency", section: "Biaya" },
    { key: "actualLaborCost", label: { id: "Tenaga Kerja Aktual", en: "Actual Labor Cost" }, widget: "Currency", section: "Biaya" },
    { key: "actualOverheadCost", label: { id: "Overhead Aktual", en: "Actual Overhead Cost" }, widget: "Currency", section: "Biaya" },
    { key: "variance", label: { id: "Variance Produksi", en: "Production Variance" }, widget: "Currency", section: "Biaya" },
    { key: "qcStatus", label: { id: "Status QC", en: "QC Status" }, widget: "TextField", section: "Status" },
    {
      key: "status",
      label: { id: "Status Produksi", en: "Production Status" },
      widget: "Select",
      section: "Status",
      options: [
        { value: "Draft", label: "Draft" },
        { value: "In Progress", label: "In Progress" },
        { value: "Quality Check", label: "Quality Check" },
        { value: "Completed", label: "Completed" },
        { value: "Cancelled", label: "Cancelled" },
      ],
    },
  ],
  listView: {
    columns: [
      { field: "id", width: "w-36" },
      { field: "productName" },
      { field: "workstation" },
      { field: "targetQty", align: "right" },
      { field: "completedQty", align: "right" },
      { field: "plannedCost", align: "right" },
      { field: "variance", align: "right" },
      { field: "status", align: "center" },
    ],
    filters: [
      {
        field: "status",
        label: { id: "Status", en: "Status" },
        widget: "Select",
        options: [
          { value: "Draft", label: "Draft" },
          { value: "In Progress", label: "In Progress" },
          { value: "Quality Check", label: "Quality Check" },
          { value: "Completed", label: "Completed" },
        ],
      },
    ],
    defaultSort: { field: "startDate", dir: "desc" },
    pageSize: 15,
    statusField: "status",
  },
  states: {
    field: "status",
    values: ["Draft", "In Progress", "Quality Check", "Completed", "Cancelled"],
    initial: "Draft",
    transitions: [
      { name: "start", label: { id: "Mulai Produksi", en: "Start Production" }, from: ["Draft"], to: "In Progress" },
      { name: "qc", label: { id: "Kirim ke QC", en: "Send to QC" }, from: ["In Progress"], to: "Quality Check" },
      { name: "finish", label: { id: "Rilis Hasil Jadi", en: "Release Finished Goods" }, from: ["Quality Check"], to: "Completed", posting: true },
      { name: "cancel", label: { id: "Batalkan SPK", en: "Cancel WO" }, from: ["Draft"], to: "Cancelled" },
    ],
  },
  permissions: {
    "System Manager": { read: true, write: true, submit: true, delete: true },
    "Stock User": { read: true, write: true, submit: true, delete: false },
  },
};

// 3. Food Roasters (food-roasters)
export const ROASTING_BATCH_META: DoctypeMeta = {
  name: "RoastingBatch",
  label: { id: "Batch Penyangraian Kopi", en: "Coffee Roasting Batch" },
  module: "Roastery & QA",
  naming: "ROAST-.YYYY.-.#####",
  titleField: "origin",
  fields: [
    { key: "id", label: { id: "Nomor Batch", en: "Batch No" }, widget: "TextField", readOnly: true },
    { key: "companyId", label: { id: "Perusahaan", en: "Company" }, widget: "TextField", readOnly: true },
    { key: "contractId", label: { id: "Kontrak Green Bean", en: "Green Bean Contract" }, widget: "TextField", section: "Bahan Baku" },
    { key: "lotCode", label: { id: "Kode Lot Green Bean", en: "Green Bean Lot" }, widget: "TextField", required: true, section: "Bahan Baku" },
    { key: "origin", label: { id: "Asal Kopi (Origin)", en: "Origin" }, widget: "TextField", required: true, section: "Bahan Baku" },
    { key: "profile", label: { id: "Profil Sangrai", en: "Roast Profile" }, widget: "TextField", section: "Proses" },
    { key: "greenWeightKg", label: { id: "Berat Green (kg)", en: "Green Weight (kg)" }, widget: "TextField", required: true, section: "Proses" },
    { key: "roastedWeightKg", label: { id: "Berat Roasted (kg)", en: "Roasted Weight (kg)" }, widget: "TextField", section: "Proses" },
    { key: "greenCost", label: { id: "Biaya Green Bean", en: "Green Bean Cost" }, widget: "Currency", section: "Biaya" },
    { key: "energyCost", label: { id: "Biaya Energi", en: "Energy Cost" }, widget: "Currency", section: "Biaya" },
    { key: "batchCost", label: { id: "Total Biaya Batch", en: "Batch Cost" }, widget: "Currency", section: "Biaya" },
    { key: "roastLossPct", label: { id: "Susut Roasting (%)", en: "Roast Loss (%)" }, widget: "TextField", section: "Proses" },
    { key: "cuppingScore", label: { id: "Skor Cupping (SCA)", en: "Cupping Score" }, widget: "TextField", section: "Quality" },
    { key: "qcStatus", label: { id: "Status QC", en: "QC Status" }, widget: "TextField", section: "Quality" },
    { key: "moisturePct", label: { id: "Moisture (%)", en: "Moisture (%)" }, widget: "TextField", section: "Quality" },
    { key: "agtron", label: { id: "Agtron", en: "Agtron" }, widget: "TextField", section: "Quality" },
    { key: "packagingId", label: { id: "Dokumen Packaging", en: "Packaging Document" }, widget: "TextField", section: "Packaging" },
    { key: "sku", label: { id: "SKU", en: "SKU" }, widget: "TextField", section: "Packaging" },
    { key: "bagCount", label: { id: "Jumlah Kemasan", en: "Bag Count" }, widget: "TextField", section: "Packaging" },
    { key: "bagSizeGrams", label: { id: "Ukuran Kemasan (gram)", en: "Bag Size (grams)" }, widget: "TextField", section: "Packaging" },
    { key: "packagedWeightKg", label: { id: "Berat Dikemas (kg)", en: "Packaged Weight (kg)" }, widget: "TextField", section: "Packaging" },
    { key: "saleId", label: { id: "Dokumen Penjualan", en: "Sale Document" }, widget: "TextField", section: "Penjualan" },
    { key: "grossMargin", label: { id: "Gross Margin", en: "Gross Margin" }, widget: "Currency", section: "Penjualan" },
    { key: "roasterOperator", label: { id: "Operator Roaster", en: "Roaster Operator" }, widget: "TextField", section: "Info" },
    { key: "roastDate", label: { id: "Tanggal Sangrai", en: "Roast Date" }, widget: "Date", section: "Info" },
    {
      key: "status",
      label: { id: "Status Batch", en: "Batch Status" },
      widget: "Select",
      section: "Status",
      options: [
        { value: "Scheduled", label: "Scheduled" },
        { value: "Roasting", label: "Roasting" },
        { value: "Cupping Passed", label: "Cupping Passed" },
        { value: "Packaged", label: "Packaged" },
      ],
    },
  ],
  listView: {
    columns: [
      { field: "id", width: "w-32" },
      { field: "origin" },
      { field: "profile" },
      { field: "greenWeightKg", align: "right" },
      { field: "batchCost", align: "right" },
      { field: "cuppingScore", align: "center" },
      { field: "grossMargin", align: "right" },
      { field: "status", align: "center" },
    ],
    filters: [
      {
        field: "status",
        label: { id: "Status", en: "Status" },
        widget: "Select",
        options: [
          { value: "Scheduled", label: "Scheduled" },
          { value: "Roasting", label: "Roasting" },
          { value: "Cupping Passed", label: "Cupping Passed" },
          { value: "Packaged", label: "Packaged" },
        ],
      },
    ],
    defaultSort: { field: "roastDate", dir: "desc" },
    pageSize: 15,
    statusField: "status",
  },
  states: {
    field: "status",
    values: ["Scheduled", "Roasting", "Cupping Passed", "Packaged"],
    initial: "Scheduled",
    transitions: [
      { name: "roast", label: { id: "Mulai Roasting", en: "Start Roasting" }, from: ["Scheduled"], to: "Roasting" },
      { name: "cup", label: { id: "Lolos Uji Rasa", en: "Pass Cupping" }, from: ["Roasting"], to: "Cupping Passed" },
      { name: "package", label: { id: "Kemas & Simpan", en: "Package Batch" }, from: ["Cupping Passed"], to: "Packaged", posting: true },
    ],
  },
  permissions: {
    "System Manager": { read: true, write: true, submit: true, delete: true },
  },
};

// 4. EPC Contractor (epc-contractor)
export const PROJECT_MILESTONE_META: DoctypeMeta = {
  name: "ProjectMilestone",
  label: { id: "Milestone Proyek & BAST", en: "Project Milestone & BAST" },
  module: "Proyek & Konstruksi",
  naming: "MLS-.YYYY.-.#####",
  titleField: "projectName",
  fields: [
    { key: "id", label: { id: "Kode Milestone", en: "Milestone ID" }, widget: "TextField", readOnly: true },
    { key: "companyId", label: { id: "Perusahaan", en: "Company" }, widget: "TextField", readOnly: true },
    { key: "projectCode", label: { id: "Kode Proyek", en: "Project Code" }, widget: "TextField", required: true, section: "Proyek" },
    { key: "projectName", label: { id: "Nama Proyek EPC", en: "Project Name" }, widget: "TextField", required: true, section: "Proyek" },
    { key: "milestoneName", label: { id: "Tahap Milestone", en: "Milestone Phase" }, widget: "TextField", required: true, section: "Progres" },
    { key: "weightPercentage", label: { id: "Bobot WBS (%)", en: "WBS Weight (%)" }, widget: "TextField", section: "Progres" },
    { key: "actualProgress", label: { id: "Progres Nyata (%)", en: "Actual Progress (%)" }, widget: "TextField", section: "Progres" },
    { key: "certifiedProgress", label: { id: "PoC Tersertifikasi (%)", en: "Certified PoC (%)" }, widget: "TextField", section: "Progres" },
    { key: "contractValue", label: { id: "Nilai Termin", en: "Milestone Value" }, widget: "Currency", required: true, section: "Finansial" },
    { key: "estimatedCost", label: { id: "Estimasi Biaya", en: "Estimated Cost" }, widget: "Currency", section: "Finansial" },
    { key: "costIncurred", label: { id: "Biaya Terjadi", en: "Cost Incurred" }, widget: "Currency", section: "Finansial" },
    { key: "revenueRecognized", label: { id: "Revenue Diakui", en: "Revenue Recognized" }, widget: "Currency", section: "Finansial" },
    { key: "margin", label: { id: "Margin PoC", en: "PoC Margin" }, widget: "Currency", section: "Finansial" },
    { key: "billingId", label: { id: "Progress Billing", en: "Progress Billing" }, widget: "TextField", section: "Billing" },
    { key: "retentionAmount", label: { id: "Retensi", en: "Retention" }, widget: "Currency", section: "Billing" },
    { key: "netBillable", label: { id: "Net Tagihan", en: "Net Billable" }, widget: "Currency", section: "Billing" },
    { key: "bastNo", label: { id: "Nomor BAST", en: "BAST No" }, widget: "TextField", section: "BAST" },
    { key: "date", label: { id: "Tanggal Verifikasi", en: "Verification Date" }, widget: "Date", section: "Info" },
    {
      key: "status",
      label: { id: "Status BAST", en: "BAST Status" },
      widget: "Select",
      section: "Status",
      options: [
        { value: "In Progress", label: "In Progress" },
        { value: "On Schedule", label: "On Schedule" },
        { value: "Certified PoC", label: "Certified PoC" },
        { value: "Billed", label: "Billed" },
        { value: "Verified BAST", label: "Verified BAST" },
      ],
    },
  ],
  listView: {
    columns: [
      { field: "id", width: "w-32" },
      { field: "projectName" },
      { field: "milestoneName" },
      { field: "actualProgress", align: "center" },
      { field: "certifiedProgress", align: "center" },
      { field: "contractValue", align: "right" },
      { field: "retentionAmount", align: "right" },
      { field: "status", align: "center" },
    ],
    filters: [
      {
        field: "status",
        label: { id: "Status", en: "Status" },
        widget: "Select",
        options: [
          { value: "In Progress", label: "In Progress" },
          { value: "On Schedule", label: "On Schedule" },
          { value: "Certified PoC", label: "Certified PoC" },
          { value: "Billed", label: "Billed" },
          { value: "Verified BAST", label: "Verified BAST" },
        ],
      },
    ],
    defaultSort: { field: "date", dir: "desc" },
    pageSize: 15,
    statusField: "status",
  },
  states: {
    field: "status",
    values: ["In Progress", "On Schedule", "Certified PoC", "Billed", "Verified BAST"],
    initial: "In Progress",
    transitions: [
      { name: "progress", label: { id: "Update Progress", en: "Update Progress" }, from: ["In Progress"], to: "On Schedule" },
      { name: "certify", label: { id: "Certify PoC", en: "Certify PoC" }, from: ["On Schedule"], to: "Certified PoC", posting: true },
      { name: "bill", label: { id: "Ajukan Tagihan", en: "Submit Billing" }, from: ["Certified PoC"], to: "Billed", posting: true },
      { name: "verify", label: { id: "Terbitkan BAST", en: "Issue BAST" }, from: ["Billed"], to: "Verified BAST", posting: true },
    ],
  },
  permissions: {
    "System Manager": { read: true, write: true, submit: true, delete: true },
  },
};

// 5. CRM Pipeline (crm-pipeline)
export const OPPORTUNITY_META: DoctypeMeta = {
  name: "Opportunity",
  label: { id: "Peluang Penjualan (Opportunity)", en: "Sales Opportunity" },
  module: "CRM & Pipeline",
  naming: "OPP-.YYYY.-.#####",
  titleField: "title",
  fields: [
    { key: "id", label: { id: "ID Peluang", en: "Opportunity ID" }, widget: "TextField", readOnly: true },
    { key: "companyId", label: { id: "Perusahaan", en: "Company" }, widget: "TextField", readOnly: true },
    { key: "title", label: { id: "Judul Deal", en: "Deal Title" }, widget: "TextField", required: true, section: "Deal Info" },
    { key: "customer", label: { id: "Prospek / Klien", en: "Prospect / Client" }, widget: "TextField", required: true, section: "Deal Info" },
    { key: "source", label: { id: "Sumber Lead", en: "Lead Source" }, widget: "TextField", section: "Deal Info" },
    { key: "leadScore", label: { id: "Skor Lead", en: "Lead Score" }, widget: "TextField", section: "Deal Info" },
    { key: "dealValue", label: { id: "Estimasi Nilai", en: "Deal Value" }, widget: "Currency", required: true, section: "Finansial" },
    { key: "probability", label: { id: "Probabilitas (%)", en: "Probability (%)" }, widget: "TextField", section: "Finansial" },
    { key: "weightedValue", label: { id: "Forecast Tertimbang", en: "Weighted Forecast" }, widget: "Currency", section: "Finansial" },
    { key: "quoteId", label: { id: "No. Quote", en: "Quote No." }, widget: "TextField", section: "Finansial" },
    { key: "assignedAgent", label: { id: "Sales Representative", en: "Sales Rep" }, widget: "TextField", section: "Penugasan" },
    { key: "expectedCloseDate", label: { id: "Estimasi Closing", en: "Expected Close" }, widget: "Date", section: "Penugasan" },
    { key: "qualificationStatus", label: { id: "Status Kualifikasi", en: "Qualification Status" }, widget: "TextField", section: "Penugasan" },
    { key: "forecastCategory", label: { id: "Kategori Forecast", en: "Forecast Category" }, widget: "TextField", section: "Penugasan" },
    { key: "contractNo", label: { id: "No. Kontrak", en: "Contract No." }, widget: "TextField", section: "Penugasan" },
    {
      key: "stage",
      label: { id: "Tahap Pipeline", en: "Pipeline Stage" },
      widget: "Select",
      section: "Tahap",
      options: [
        { value: "Lead Baru", label: "Lead Baru" },
        { value: "Kualifikasi", label: "Kualifikasi" },
        { value: "Proposal", label: "Proposal" },
        { value: "Negosiasi", label: "Negosiasi" },
        { value: "Won", label: "Won" },
        { value: "Lost", label: "Lost" },
      ],
    },
  ],
  listView: {
    columns: [
      { field: "id", width: "w-32" },
      { field: "title" },
      { field: "customer" },
      { field: "dealValue", align: "right" },
      { field: "probability", align: "right" },
      { field: "weightedValue", align: "right" },
      { field: "stage", align: "center" },
    ],
    filters: [
      {
        field: "stage",
        label: { id: "Tahap", en: "Stage" },
        widget: "Select",
        options: [
          { value: "Lead Baru", label: "Lead Baru" },
          { value: "Kualifikasi", label: "Kualifikasi" },
          { value: "Proposal", label: "Proposal" },
          { value: "Negosiasi", label: "Negosiasi" },
          { value: "Won", label: "Won" },
        ],
      },
    ],
    defaultSort: { field: "dealValue", dir: "desc" },
    pageSize: 15,
    statusField: "stage",
  },
  states: {
    field: "stage",
    values: ["Lead Baru", "Kualifikasi", "Proposal", "Negosiasi", "Won", "Lost"],
    initial: "Lead Baru",
    transitions: [
      { name: "propose", label: { id: "Kirim Proposal", en: "Send Proposal" }, from: ["Lead Baru", "Kualifikasi"], to: "Proposal" },
      { name: "negotiate", label: { id: "Mulai Negosiasi", en: "Negotiate" }, from: ["Proposal"], to: "Negosiasi" },
      { name: "win", label: { id: "Tutup Deal (Won)", en: "Close Won" }, from: ["Proposal", "Negosiasi"], to: "Won", posting: true },
      { name: "lose", label: { id: "Tandai Kalah (Lost)", en: "Mark Lost" }, from: ["Lead Baru", "Kualifikasi", "Proposal", "Negosiasi"], to: "Lost" },
    ],
  },
  permissions: {
    "System Manager": { read: true, write: true, submit: true, delete: true },
    "Sales User": { read: true, write: true, submit: true, delete: false },
  },
};

// 6. Koperasi BMT (koperasi-bmt)
export const MURABAHAH_FINANCING_META: DoctypeMeta = {
  name: "MurabahahAgreement",
  label: { id: "Akad Pembiayaan Murabahah", en: "Murabahah Financing Agreement" },
  module: "BMT & Pembiayaan Syariah",
  naming: "AKAD-MRB-.YYYY.-.#####",
  titleField: "memberName",
  fields: [
    { key: "id", label: { id: "Nomor Akad", en: "Agreement No" }, widget: "TextField", readOnly: true },
    { key: "companyId", label: { id: "Perusahaan", en: "Company" }, widget: "TextField", readOnly: true },
    { key: "memberId", label: { id: "Nomor Anggota", en: "Member ID" }, widget: "TextField", required: true, section: "Anggota" },
    { key: "memberName", label: { id: "Nama Anggota", en: "Member Name" }, widget: "TextField", required: true, section: "Anggota" },
    { key: "goodsDescription", label: { id: "Objek Barang", en: "Goods Description" }, widget: "TextField", required: true, section: "Pembiayaan" },
    { key: "principalAmount", label: { id: "Harga Pokok (Pokok)", en: "Principal Amount" }, widget: "Currency", required: true, section: "Finansial" },
    { key: "marginAmount", label: { id: "Margin Keuntungan", en: "Margin Amount" }, widget: "Currency", section: "Finansial" },
    { key: "totalFinancing", label: { id: "Total Pembiayaan", en: "Total Financing" }, widget: "Currency", required: true, section: "Finansial" },
    { key: "monthlyInstallment", label: { id: "Angsuran per Bulan", en: "Monthly Installment" }, widget: "Currency", section: "Finansial" },
    { key: "tenorMonths", label: { id: "Tenor (bulan)", en: "Tenor (months)" }, widget: "TextField", section: "Jadwal" },
    { key: "outstandingPrincipal", label: { id: "Sisa Pokok", en: "Outstanding Principal" }, widget: "Currency", section: "Saldo" },
    { key: "outstandingMargin", label: { id: "Sisa Margin", en: "Outstanding Margin" }, widget: "Currency", section: "Saldo" },
    { key: "paidPrincipal", label: { id: "Pokok Terbayar", en: "Paid Principal" }, widget: "Currency", section: "Saldo" },
    { key: "paidMargin", label: { id: "Margin Terbayar", en: "Paid Margin" }, widget: "Currency", section: "Saldo" },
    { key: "collectibilityGrade", label: { id: "Kolektibilitas", en: "Collectibility" }, widget: "TextField", section: "Risiko" },
    { key: "daysPastDue", label: { id: "Hari Tunggakan", en: "Days Past Due" }, widget: "TextField", section: "Risiko" },
    { key: "ckpnReserve", label: { id: "CKPN", en: "Provision Reserve" }, widget: "Currency", section: "Risiko" },
    { key: "approvedBy", label: { id: "Disetujui Oleh", en: "Approved By" }, widget: "TextField", section: "Approval" },
    { key: "approvedAt", label: { id: "Tanggal Persetujuan", en: "Approved At" }, widget: "Date", section: "Approval" },
    { key: "disbursedAt", label: { id: "Tanggal Pencairan", en: "Disbursed At" }, widget: "Date", section: "Approval" },
    { key: "startDate", label: { id: "Tanggal Akad", en: "Agreement Date" }, widget: "Date", section: "Jadwal" },
    {
      key: "status",
      label: { id: "Status Akad", en: "Agreement Status" },
      widget: "Select",
      section: "Status",
      options: [
        { value: "Pengajuan", label: "Pengajuan" },
        { value: "Disetujui", label: "Disetujui" },
        { value: "Aktif", label: "Aktif" },
        { value: "Lunas", label: "Lunas" },
      ],
    },
  ],
  listView: {
    columns: [
      { field: "id", width: "w-36" },
      { field: "memberName" },
      { field: "goodsDescription" },
      { field: "principalAmount", align: "right" },
      { field: "totalFinancing", align: "right" },
      { field: "outstandingPrincipal", align: "right" },
      { field: "collectibilityGrade", align: "center" },
      { field: "status", align: "center" },
    ],
    filters: [
      {
        field: "status",
        label: { id: "Status", en: "Status" },
        widget: "Select",
        options: [
          { value: "Pengajuan", label: "Pengajuan" },
          { value: "Disetujui", label: "Disetujui" },
          { value: "Aktif", label: "Aktif" },
          { value: "Lunas", label: "Lunas" },
        ],
      },
    ],
    defaultSort: { field: "startDate", dir: "desc" },
    pageSize: 15,
    statusField: "status",
  },
  states: {
    field: "status",
    values: ["Pengajuan", "Disetujui", "Aktif", "Lunas"],
    initial: "Pengajuan",
    transitions: [
      { name: "approve", label: { id: "Setujui Akad", en: "Approve Financing" }, from: ["Pengajuan"], to: "Disetujui" },
      { name: "disburse", label: { id: "Cairkan Dana", en: "Disburse Funds" }, from: ["Disetujui"], to: "Aktif", posting: true },
      { name: "settle", label: { id: "Tutup / Lunas", en: "Settle Full" }, from: ["Aktif"], to: "Lunas", posting: true },
    ],
  },
  permissions: {
    "System Manager": { read: true, write: true, submit: true, delete: true },
  },
};

// 7. Hospital Medika (hospital-medika)
export const PATIENT_ADMISSION_META: DoctypeMeta = {
  name: "PatientAdmission",
  label: { id: "Pendaftaran & Rekam Medis Pasien", en: "Patient Admission & EMR" },
  module: "Pelayanan Medis & EMR",
  naming: "REG-MED-.YYYY.-.#####",
  titleField: "patientName",
  fields: [
    { key: "id", label: { id: "Nomor Registrasi", en: "Registration No" }, widget: "TextField", readOnly: true },
    { key: "companyId", label: { id: "Perusahaan", en: "Company" }, widget: "TextField", readOnly: true },
    { key: "patientName", label: { id: "Nama Pasien", en: "Patient Name" }, widget: "TextField", required: true, section: "Pasien" },
    { key: "medicalRecordNo", label: { id: "No. Rekam Medis (RM)", en: "Medical Record No" }, widget: "TextField", required: true, section: "Pasien" },
    { key: "queueNo", label: { id: "Nomor Antrean", en: "Queue No" }, widget: "TextField", section: "Pelayanan" },
    { key: "polyDepartment", label: { id: "Poliklinik", en: "Polyclinic" }, widget: "TextField", required: true, section: "Pelayanan" },
    { key: "doctorName", label: { id: "Dokter Penanggung Jawab", en: "Attending Doctor" }, widget: "TextField", section: "Pelayanan" },
    { key: "insuranceType", label: { id: "Jaminan Asuransi", en: "Insurance Type" }, widget: "TextField", section: "Pelayanan" },
    { key: "encounterId", label: { id: "Encounter", en: "Encounter" }, widget: "TextField", section: "EMR" },
    { key: "emrId", label: { id: "Dokumen EMR", en: "EMR Document" }, widget: "TextField", section: "EMR" },
    { key: "icd10Code", label: { id: "Kode ICD-10", en: "ICD-10 Code" }, widget: "TextField", section: "EMR" },
    { key: "diagnosisText", label: { id: "Diagnosa", en: "Diagnosis" }, widget: "TextField", section: "EMR" },
    { key: "prescriptionId", label: { id: "No. Resep", en: "Prescription No" }, widget: "TextField", section: "Farmasi" },
    { key: "drugBatchId", label: { id: "Batch Obat FEFO", en: "FEFO Drug Batch" }, widget: "TextField", section: "Farmasi" },
    { key: "billId", label: { id: "No. Billing", en: "Bill No" }, widget: "TextField", section: "Billing" },
    { key: "billAmount", label: { id: "Nilai Billing", en: "Bill Amount" }, widget: "Currency", section: "Billing" },
    { key: "claimId", label: { id: "No. Klaim", en: "Claim No" }, widget: "TextField", section: "Klaim" },
    { key: "claimStatus", label: { id: "Status Klaim", en: "Claim Status" }, widget: "TextField", section: "Klaim" },
    { key: "admissionDate", label: { id: "Tanggal Daftar", en: "Admission Date" }, widget: "Date", section: "Waktu" },
    {
      key: "status",
      label: { id: "Status Pelayanan", en: "Status" },
      widget: "Select",
      section: "Status",
      options: [
        { value: "Menunggu Dokter", label: "Menunggu Dokter" },
        { value: "Pemeriksaan", label: "Pemeriksaan" },
        { value: "Apotek Resep", label: "Apotek Resep" },
        { value: "Selesai", label: "Selesai" },
        { value: "Rawat Inap", label: "Rawat Inap" },
      ],
    },
  ],
  listView: {
    columns: [
      { field: "id", width: "w-36" },
      { field: "patientName" },
      { field: "medicalRecordNo" },
      { field: "queueNo", align: "center" },
      { field: "polyDepartment" },
      { field: "icd10Code", align: "center" },
      { field: "insuranceType" },
      { field: "claimStatus", align: "center" },
      { field: "status", align: "center" },
    ],
    filters: [
      {
        field: "status",
        label: { id: "Status", en: "Status" },
        widget: "Select",
        options: [
          { value: "Menunggu Dokter", label: "Menunggu Dokter" },
          { value: "Pemeriksaan", label: "Pemeriksaan" },
          { value: "Apotek Resep", label: "Apotek Resep" },
          { value: "Selesai", label: "Selesai" },
        ],
      },
    ],
    defaultSort: { field: "admissionDate", dir: "desc" },
    pageSize: 15,
    statusField: "status",
  },
  states: {
    field: "status",
    values: ["Menunggu Dokter", "Pemeriksaan", "Apotek Resep", "Selesai", "Rawat Inap"],
    initial: "Menunggu Dokter",
    transitions: [
      { name: "examine", label: { id: "Panggil Pemeriksaan", en: "Start Examination" }, from: ["Menunggu Dokter"], to: "Pemeriksaan" },
      { name: "prescribe", label: { id: "Kirim ke Farmasi", en: "Send Prescription" }, from: ["Pemeriksaan"], to: "Apotek Resep" },
      { name: "complete", label: { id: "Selesaikan Kunjungan", en: "Complete Visit" }, from: ["Apotek Resep"], to: "Selesai", posting: true },
    ],
  },
  permissions: {
    "System Manager": { read: true, write: true, submit: true, delete: true },
  },
};

// 8. Medical Device (medical-device)
export const DEVICE_BATCH_META: DoctypeMeta = {
  name: "DeviceBatch",
  label: { id: "Batch Produksi Alat Kesehatan (DHR)", en: "Medical Device Batch (DHR)" },
  module: "ISO 13485 & DMR/DHR",
  naming: "LOT-MD-.YYYY.-.#####",
  titleField: "deviceName",
  fields: [
    { key: "id", label: { id: "Nomor Lot / Batch", en: "Lot / Batch No" }, widget: "TextField", readOnly: true },
    { key: "companyId", label: { id: "Perusahaan", en: "Company" }, widget: "TextField", readOnly: true },
    { key: "dmrId", label: { id: "Device Master Record", en: "Device Master Record" }, widget: "TextField", section: "DMR/DHR" },
    { key: "dhrId", label: { id: "Device History Record", en: "Device History Record" }, widget: "TextField", section: "DMR/DHR" },
    { key: "deviceName", label: { id: "Nama Perangkat Medis", en: "Device Name" }, widget: "TextField", required: true, section: "Produk" },
    { key: "riskClass", label: { id: "Kelas Risiko", en: "Risk Class" }, widget: "TextField", section: "Produk" },
    { key: "batchQty", label: { id: "Jumlah Batch (pcs)", en: "Batch Qty" }, widget: "TextField", required: true, section: "Produk" },
    { key: "unitCost", label: { id: "Biaya per Unit", en: "Unit Cost" }, widget: "Currency", section: "Biaya" },
    { key: "udiCode", label: { id: "Kode UDI", en: "UDI Code" }, widget: "TextField", required: true, section: "Kepatuhan" },
    { key: "cleanroomClass", label: { id: "Kelas Cleanroom", en: "Cleanroom Class" }, widget: "TextField", section: "Kepatuhan" },
    { key: "sterilizationMethod", label: { id: "Metode Sterilisasi", en: "Sterilization Method" }, widget: "TextField", section: "Kepatuhan" },
    { key: "cleanroomInspectionId", label: { id: "Inspeksi Cleanroom", en: "Cleanroom Inspection" }, widget: "TextField", section: "Kepatuhan" },
    { key: "sterilizationCycleId", label: { id: "Siklus Sterilisasi", en: "Sterilization Cycle" }, widget: "TextField", section: "Kepatuhan" },
    { key: "capaId", label: { id: "CAPA Aktif", en: "Active CAPA" }, widget: "TextField", section: "CAPA" },
    { key: "qaHold", label: { id: "QA Hold", en: "QA Hold" }, widget: "TextField", section: "CAPA" },
    { key: "qaReleaseId", label: { id: "Dokumen QA Release", en: "QA Release" }, widget: "TextField", section: "QA Release" },
    { key: "udiTraceId", label: { id: "UDI Trace Event", en: "UDI Trace Event" }, widget: "TextField", section: "QA Release" },
    { key: "manufacturingDate", label: { id: "Tanggal Produksi", en: "Mfg Date" }, widget: "Date", section: "Info" },
    {
      key: "status",
      label: { id: "Status QA/DHR", en: "QA/DHR Status" },
      widget: "Select",
      section: "Status",
      options: [
        { value: "In Assembly", label: "In Assembly" },
        { value: "Cleanroom Passed", label: "Cleanroom Passed" },
        { value: "Sterilization Passed", label: "Sterilization Passed" },
        { value: "QA Released", label: "QA Released" },
      ],
    },
  ],
  listView: {
    columns: [
      { field: "id", width: "w-32" },
      { field: "deviceName" },
      { field: "dmrId", align: "center" },
      { field: "batchQty", align: "right" },
      { field: "udiCode" },
      { field: "qaHold", align: "center" },
      { field: "status", align: "center" },
    ],
    filters: [
      {
        field: "status",
        label: { id: "Status", en: "Status" },
        widget: "Select",
        options: [
          { value: "In Assembly", label: "In Assembly" },
          { value: "Cleanroom Passed", label: "Cleanroom Passed" },
          { value: "Sterilization Passed", label: "Sterilization Passed" },
          { value: "QA Released", label: "QA Released" },
        ],
      },
    ],
    defaultSort: { field: "manufacturingDate", dir: "desc" },
    pageSize: 15,
    statusField: "status",
  },
  states: {
    field: "status",
    values: ["In Assembly", "Cleanroom Passed", "Sterilization Passed", "QA Released"],
    initial: "In Assembly",
    transitions: [
      { name: "cleanroom", label: { id: "Lolos Cleanroom", en: "Pass Cleanroom" }, from: ["In Assembly"], to: "Cleanroom Passed" },
      { name: "sterilize", label: { id: "Lolos Sterilisasi", en: "Pass Sterilization" }, from: ["Cleanroom Passed"], to: "Sterilization Passed" },
      { name: "release", label: { id: "Rilis DHR (QA Released)", en: "QA Release Batch" }, from: ["Sterilization Passed"], to: "QA Released", posting: true },
    ],
  },
  permissions: {
    "System Manager": { read: true, write: true, submit: true, delete: true },
  },
};

// 9. Omnichannel Distribution (omnichannel-dist)
export const FULFILLMENT_ORDER_META: DoctypeMeta = {
  name: "FulfillmentOrder",
  label: { id: "Pesanan Fulfillment Omnichannel", en: "Omnichannel Fulfillment Order" },
  module: "Marketplace & WMS",
  naming: "FUL-OMNI-.YYYY.-.#####",
  titleField: "marketplaceOrderNo",
  fields: [
    { key: "id", label: { id: "Nomor Fulfillment", en: "Fulfillment ID" }, widget: "TextField", readOnly: true },
    { key: "companyId", label: { id: "Perusahaan", en: "Company" }, widget: "TextField", readOnly: true },
    { key: "marketplaceOrderNo", label: { id: "Nomor Invoice MP", en: "Marketplace Invoice" }, widget: "TextField", required: true, section: "Marketplace" },
    { key: "channel", label: { id: "Kanal Penjualan", en: "Sales Channel" }, widget: "TextField", required: true, section: "Marketplace" },
    { key: "customerName", label: { id: "Nama Pembeli", en: "Buyer Name" }, widget: "TextField", required: true, section: "Marketplace" },
    { key: "grossAmount", label: { id: "GMV", en: "Gross Amount" }, widget: "Currency", section: "Marketplace" },
    { key: "courier", label: { id: "Ekspedisi / Kurir", en: "Courier Service" }, widget: "TextField", section: "Pengiriman" },
    { key: "trackingNo", label: { id: "Nomor Resi", en: "Tracking No" }, widget: "TextField", section: "Pengiriman" },
    { key: "warehouse", label: { id: "Gudang / Hub", en: "Warehouse / Hub" }, widget: "TextField", section: "Pengiriman" },
    { key: "waveId", label: { id: "Wave Picking", en: "Picking Wave" }, widget: "TextField", section: "Pengiriman" },
    { key: "picker", label: { id: "Picker", en: "Picker" }, widget: "TextField", section: "Pengiriman" },
    { key: "totalItems", label: { id: "Jumlah Item", en: "Total Items" }, widget: "TextField", default: 1, section: "Pengiriman" },
    { key: "orderDate", label: { id: "Tanggal Pesanan", en: "Order Date" }, widget: "Date", section: "Waktu" },
    { key: "settlementStatus", label: { id: "Status Settlement", en: "Settlement Status" }, widget: "TextField", section: "Marketplace" },
    { key: "netSettlement", label: { id: "Dana Cair", en: "Net Settlement" }, widget: "Currency", section: "Marketplace" },
    {
      key: "status",
      label: { id: "Status WMS", en: "WMS Status" },
      widget: "Select",
      section: "Status",
      options: [
        { value: "Synced", label: "Synced" },
        { value: "Wave Assigned", label: "Wave Assigned" },
        { value: "Picking", label: "Picking" },
        { value: "Packing", label: "Packing" },
        { value: "Shipped", label: "Shipped" },
        { value: "Delivered", label: "Delivered" },
      ],
    },
  ],
  listView: {
    columns: [
      { field: "id", width: "w-36" },
      { field: "marketplaceOrderNo" },
      { field: "channel" },
      { field: "grossAmount", align: "right" },
      { field: "courier" },
      { field: "trackingNo" },
      { field: "status", align: "center" },
    ],
    filters: [
      {
        field: "status",
        label: { id: "Status", en: "Status" },
        widget: "Select",
        options: [
          { value: "Synced", label: "Synced" },
          { value: "Wave Assigned", label: "Wave Assigned" },
          { value: "Picking", label: "Picking" },
          { value: "Packing", label: "Packing" },
          { value: "Shipped", label: "Shipped" },
        ],
      },
    ],
    defaultSort: { field: "orderDate", dir: "desc" },
    pageSize: 15,
    statusField: "status",
  },
  states: {
    field: "status",
    values: ["Synced", "Wave Assigned", "Picking", "Packing", "Shipped", "Delivered"],
    initial: "Synced",
    transitions: [
      { name: "reserve", label: { id: "Reservasi Stok", en: "Reserve Stock" }, from: ["Synced"], to: "Wave Assigned" },
      { name: "pick", label: { id: "Mulai Picking", en: "Start Picking" }, from: ["Wave Assigned"], to: "Picking" },
      { name: "pack", label: { id: "Selesai Packing", en: "Complete Packing" }, from: ["Picking"], to: "Packing" },
      { name: "ship", label: { id: "Serahkan ke Kurir", en: "Handover to Courier" }, from: ["Packing"], to: "Shipped", posting: true },
      { name: "deliver", label: { id: "Pesanan Diterima", en: "Order Delivered" }, from: ["Shipped"], to: "Delivered" },
    ],
  },
  permissions: {
    "System Manager": { read: true, write: true, submit: true, delete: true },
  },
};

// 10. Help Desk (helpdesk)
export const SUPPORT_TICKET_META: DoctypeMeta = {
  name: "SupportTicket",
  label: { id: "Tiket Bantuan Pelanggan", en: "Customer Support Ticket" },
  module: "Help Desk & SLA",
  naming: "HD-TICK-.YYYY.-.#####",
  titleField: "subject",
  fields: [
    { key: "id", label: { id: "ID Tiket", en: "Ticket ID" }, widget: "TextField", readOnly: true },
    { key: "subject", label: { id: "Subjek Masalah", en: "Subject" }, widget: "TextField", required: true, section: "Detail Tiket" },
    { key: "customerName", label: { id: "Pengirim / Pelanggan", en: "Customer" }, widget: "TextField", required: true, section: "Detail Tiket" },
    {
      key: "channel",
      label: { id: "Channel", en: "Channel" },
      widget: "Select",
      section: "Detail Tiket",
      options: [
        { value: "WhatsApp", label: "WhatsApp" },
        { value: "Portal", label: "Portal" },
        { value: "Email", label: "Email" },
        { value: "API Hook", label: "API Hook" },
      ],
    },
    {
      key: "priority",
      label: { id: "Prioritas", en: "Priority" },
      widget: "Select",
      section: "Detail Tiket",
      options: [
        { value: "Low", label: "Low" },
        { value: "Medium", label: "Medium" },
        { value: "High", label: "High" },
        { value: "Critical P1", label: "Critical P1" },
      ],
    },
    { key: "assignedAgent", label: { id: "Petugas Help Desk", en: "Assigned Agent" }, widget: "TextField", section: "Penugasan" },
    { key: "slaDueMinutes", label: { id: "Batas Waktu SLA (Menit)", en: "SLA Due (Mins)" }, widget: "TextField", section: "Penugasan" },
    { key: "createdDate", label: { id: "Tanggal Tiket", en: "Created Date" }, widget: "Date", section: "Waktu" },
    { key: "createdAt", label: { id: "Waktu Intake", en: "Intake Time" }, widget: "TextField", section: "Waktu" },
    { key: "firstResponseMinutes", label: { id: "Menit Respon Pertama", en: "First Response Minutes" }, widget: "TextField", section: "SLA" },
    { key: "firstResponseSla", label: { id: "SLA Respon", en: "Response SLA" }, widget: "TextField", section: "SLA" },
    { key: "slaStatus", label: { id: "Status SLA", en: "SLA Status" }, widget: "TextField", section: "SLA" },
    { key: "escalationLevel", label: { id: "Level Eskalasi", en: "Escalation Level" }, widget: "TextField", section: "Eskalasi" },
    { key: "escalatedTo", label: { id: "Eskalasi Ke", en: "Escalated To" }, widget: "TextField", section: "Eskalasi" },
    { key: "resolutionMinutes", label: { id: "Menit Resolusi", en: "Resolution Minutes" }, widget: "TextField", section: "Resolusi" },
    { key: "resolutionSla", label: { id: "SLA Resolusi", en: "Resolution SLA" }, widget: "TextField", section: "Resolusi" },
    { key: "csatRating", label: { id: "Rating CSAT", en: "CSAT Rating" }, widget: "TextField", section: "CSAT" },
    {
      key: "status",
      label: { id: "Status Tiket", en: "Ticket Status" },
      widget: "Select",
      section: "Status",
      options: [
        { value: "New", label: "New" },
        { value: "In Progress", label: "In Progress" },
        { value: "Waiting on Customer", label: "Waiting on Customer" },
        { value: "Resolved", label: "Resolved" },
        { value: "Closed", label: "Closed" },
      ],
    },
  ],
  listView: {
    columns: [
      { field: "id", width: "w-36" },
      { field: "subject" },
      { field: "customerName" },
      { field: "channel", align: "center" },
      { field: "priority", align: "center" },
      { field: "status", align: "center" },
    ],
    filters: [
      {
        field: "status",
        label: { id: "Status", en: "Status" },
        widget: "Select",
        options: [
          { value: "New", label: "New" },
          { value: "In Progress", label: "In Progress" },
          { value: "Waiting on Customer", label: "Waiting on Customer" },
          { value: "Resolved", label: "Resolved" },
        ],
      },
    ],
    defaultSort: { field: "createdDate", dir: "desc" },
    pageSize: 15,
    statusField: "status",
  },
  states: {
    field: "status",
    values: ["New", "In Progress", "Waiting on Customer", "Resolved", "Closed"],
    initial: "New",
    transitions: [
      { name: "progress", label: { id: "Tangani Masalah", en: "Work on Ticket" }, from: ["New", "Waiting on Customer"], to: "In Progress" },
      { name: "resolve", label: { id: "Selesaikan (Resolved)", en: "Resolve Ticket" }, from: ["In Progress"], to: "Resolved", posting: true },
      { name: "close", label: { id: "Tutup Tiket", en: "Close Ticket" }, from: ["Resolved"], to: "Closed" },
    ],
  },
  permissions: {
    "System Manager": { read: true, write: true, submit: true, delete: true },
  },
};
