import type { ComponentEventDescriptor, ComponentPropDescriptor, ComponentPropType, WidgetManifest } from "../types";
import {
  Container,
  Row,
  Column,
  Stack,
  Spacer,
  Divider,
  Text,
  Image,
  Button,
  Badge,
  TextField,
  Checkbox,
  Switch,
  Slider,
  Select,
  Textarea,
  RadioGroup,
  Form,
  ListView,
  GridView,
  DataTable,
  PageBar,
  Chart,
  KanbanBoard,
  TreeView,
  Sidebar,
  Navbar,
  Toolbar,
  Drawer,
  Panel,
  Popover,
  Dialog,
  Snackbar,
} from "../components/primitives";
import { BarcodeSVG, DataMatrixSVG, QRCodeSVG } from "../components/BarcodeAndQRCode";
import { IconWidget } from "../components/icons";

function prop(
  name: string,
  type: ComponentPropType,
  description?: string,
  options: Omit<ComponentPropDescriptor, "name" | "type" | "description"> = {},
): ComponentPropDescriptor {
  return { name, type, ...(description ? { description } : {}), ...options };
}

function event(name: string, payload: ComponentEventDescriptor["payload"], description?: string): ComponentEventDescriptor {
  return { name, payload, ...(description ? { description } : {}) };
}

const containerProps = [prop("className", "string"), prop("style", "object")];
const textProps = [
  prop("value", "string", "Visible text content.", { bindable: true }),
  prop("heading", "enum", "Render as h1-h6 instead of a paragraph.", { values: ["1", "2", "3", "4", "5", "6"] }),
  prop("format", "enum", "Print a bound numeric/date value the way a list cell would.", {
    values: ["text", "currency", "number", "integer", "date", "status", "check"],
  }),
  prop("locale", "string", "BCP 47 tag used when `format` is set."),
  prop("currency", "string", "ISO 4217 code used when `format` is `currency`."),
];
const formControlProps = [
  prop("label", "string"),
  prop("aria-label", "string", "Accessible name, for a control whose visible label is a sibling node (TwoColumnForm rows)."),

  prop("value", "string", "Controlled field value.", { bindable: true }),
  prop("placeholder", "string"),
  prop("error", "string"),
  prop("size", "enum", "Meridian control density.", { values: ["small", "large"] }),
  prop("border", "boolean"),
  prop("disabled", "boolean"),
  prop("readOnly", "boolean"),
];
const optionProps = [prop("options", "array", "Array of { value, label, disabled? } options.")];
const closeEvent = event("onClose", "close", "Fires when the component requests dismissal.");

export const defaultWidgets: WidgetManifest[] = [
  {
    type: "Container",
    component: Container,
    category: "layout",
    acceptsChildren: true,
    defaultProps: {},
    propDescriptors: containerProps,
    events: ["onClick"],
    eventDescriptors: [event("onClick", "event")],
  },
  {
    type: "Row",
    component: Row,
    category: "layout",
    acceptsChildren: true,
    defaultProps: {},
    propDescriptors: containerProps,
  },
  {
    type: "Column",
    component: Column,
    category: "layout",
    acceptsChildren: true,
    defaultProps: {},
    propDescriptors: containerProps,
  },
  {
    type: "Stack",
    component: Stack,
    category: "layout",
    acceptsChildren: true,
    defaultProps: {},
    propDescriptors: containerProps,
  },
  {
    type: "Spacer",
    component: Spacer,
    category: "layout",
    acceptsChildren: false,
    defaultProps: {},
    propDescriptors: containerProps,
  },
  {
    type: "Divider",
    component: Divider,
    category: "layout",
    acceptsChildren: false,
    defaultProps: {},
    propDescriptors: containerProps,
  },
  {
    type: "Text",
    component: Text,
    category: "base",
    acceptsChildren: false,
    defaultProps: {},
    propDescriptors: textProps,
  },
  {
    // An outline glyph addressed by name (see `ICON_NAMES`) — the schema-level replacement for
    // emoji, which do not theme, do not scale with the type ramp and read differently per OS.
    type: "Icon",
    component: IconWidget,
    category: "base",
    acceptsChildren: false,
    defaultProps: { name: "document-text" },
    propDescriptors: [
      prop("name", "string", "Icon name from ICON_NAMES."),
      prop("size", "number", "Rendered icon size in px, or pass a CSS size string."),
      prop("title", "string", "Accessible icon title."),
      prop("strokeWidth", "number"),
      prop("className", "string"),
    ],
  },
  {
    type: "Image",
    component: Image,
    category: "base",
    acceptsChildren: false,
    defaultProps: {},
    propDescriptors: [prop("src", "string"), prop("alt", "string"), prop("className", "string"), prop("style", "object")],
  },
  {
    type: "Button",
    component: Button,
    category: "base",
    acceptsChildren: false,
    defaultProps: {},
    propDescriptors: [
      prop("label", "string", "Button label text."),
      prop("variant", "enum", "Meridian button variant.", { values: ["primary", "secondary"] }),
      prop("icon", "boolean", "Use compact icon-button padding."),
      prop("iconName", "string", "Optional leading or trailing icon from ICON_NAMES."),
      prop("iconPosition", "enum", "Icon placement.", { values: ["start", "end"] }),
      prop("background", "boolean"),
      prop("padding", "boolean"),
      prop("disabled", "boolean"),
    ],
    events: ["onClick"],
    eventDescriptors: [event("onClick", "event")],
  },
  {
    type: "Badge",
    component: Badge,
    category: "base",
    acceptsChildren: true,
    defaultProps: {},
    propDescriptors: [
      prop("label", "string"),
      prop("color", "enum", "Meridian status color.", { values: ["gray", "orange", "green", "red", "yellow", "blue", "indigo", "pink", "purple", "teal"] }),
      prop("variant", "enum", "Badge size/style.", { values: ["badge", "pill"] }),
      prop("iconName", "string"),
    ],
  },
  {
    type: "TextField",
    component: TextField,
    category: "form",
    acceptsChildren: false,
    defaultProps: {},
    propDescriptors: formControlProps,
    events: ["onChange", "onBlur", "onFocus"],
    eventDescriptors: [event("onChange", "value"), event("onBlur", "event"), event("onFocus", "event")],
  },
  {
    type: "Checkbox",
    component: Checkbox,
    category: "form",
    acceptsChildren: false,
    defaultProps: {},
    propDescriptors: [prop("label", "string"), prop("aria-label", "string"), prop("checked", "boolean", "Controlled checked state.", { bindable: true }), prop("disabled", "boolean")],
    events: ["onChange"],
    eventDescriptors: [event("onChange", "value")],
  },
  {
    type: "Switch",
    component: Switch,
    category: "form",
    acceptsChildren: false,
    defaultProps: {},
    propDescriptors: [prop("checked", "boolean", "Controlled checked state.", { bindable: true }), prop("aria-label", "string")],
    events: ["onChange"],
    eventDescriptors: [event("onChange", "value")],
  },
  {
    type: "Slider",
    component: Slider,
    category: "form",
    acceptsChildren: false,
    defaultProps: {},
    propDescriptors: [prop("value", "number", "Controlled numeric value.", { bindable: true }), prop("min", "number"), prop("max", "number"), prop("disabled", "boolean"), prop("aria-label", "string")],
    events: ["onChange"],
    eventDescriptors: [event("onChange", "value")],
  },
  {
    type: "Select",
    component: Select,
    category: "form",
    acceptsChildren: false,
    defaultProps: {},
    propDescriptors: [
      ...formControlProps,
      ...optionProps,
      prop("optionValueKey", "string", "Key holding an option's stored value; lookup rows carry the target's own id."),
      prop("optionLabelKey", "string", "Key holding an option's visible text."),
    ],
    events: ["onChange", "onBlur", "onFocus"],
    eventDescriptors: [event("onChange", "value"), event("onBlur", "event"), event("onFocus", "event")],
  },
  {
    type: "Textarea",
    component: Textarea,
    category: "form",
    acceptsChildren: false,
    defaultProps: {},
    propDescriptors: [...formControlProps, prop("rows", "number")],
    events: ["onChange", "onBlur", "onFocus"],
    eventDescriptors: [event("onChange", "value"), event("onBlur", "event"), event("onFocus", "event")],
  },
  {
    type: "RadioGroup",
    component: RadioGroup,
    category: "form",
    acceptsChildren: false,
    defaultProps: {},
    propDescriptors: [prop("label", "string"), prop("name", "string"), prop("value", "string", "Controlled selected value.", { bindable: true }), ...optionProps, prop("error", "string")],
    events: ["onChange"],
    eventDescriptors: [event("onChange", "value")],
  },
  {
    type: "Form",
    component: Form,
    category: "form",
    acceptsChildren: true,
    defaultProps: {},
    propDescriptors: containerProps,
    events: ["onSubmit"],
    eventDescriptors: [event("onSubmit", "submit")],
  },
  {
    type: "ListView",
    component: ListView,
    category: "data",
    acceptsChildren: true,
    defaultProps: {},
    propDescriptors: containerProps,
  },
  {
    type: "GridView",
    component: GridView,
    category: "data",
    acceptsChildren: true,
    defaultProps: {},
    propDescriptors: containerProps,
  },
  {
    type: "DataTable",
    component: DataTable,
    category: "data",
    acceptsChildren: false,
    defaultProps: {},
    propDescriptors: [
      prop("title", "string"),
      prop("dataSource", "string", "Name of a document data source resolved to rows."),
      prop(
        "columns",
        "array",
        "Array of { key, label, align?, format? } columns. `format` is one of text | currency | number | integer | date | status | check and drives how the value is printed (status renders a coloured pill; numeric formats right-align).",
      ),
      prop("rows", "array", "Static row objects. Prefer dataSource for adapter-backed data."),
      prop("rowActions", "array", "Array of { label, event? } row actions. Omit for a Meridian-style list where the row itself opens the record."),
      prop("emptyMessage", "string"),
      prop("showIndex", "boolean"),
      prop("paginate", "boolean"),
      prop("pageSizes", "array"),
      prop("locale", "string", "BCP 47 tag used to format date and numeric cells."),
      prop("currency", "string", "ISO 4217 code used to format `currency` columns."),
    ],
    events: ["onRowAction", "onOpen"],
    eventDescriptors: [
      event("onRowAction", "rowAction", "Fires for row action buttons; named row action events are also supported."),
      event("onOpen", "rowAction", "Fires when a row is activated (click or Enter/Space), with that row's data."),
    ],
    hideFromPalette: true,
  },
  {
    type: "PageBar",
    component: PageBar,
    category: "navigation",
    acceptsChildren: false,
    defaultProps: {},
    propDescriptors: [
      prop("total", "number", "Rows in the whole result — a server total, not the loaded page.", { bindable: true }),
      prop("page", "number", "Current 1-based page.", { bindable: true }),
      prop("pageSize", "number", "Rows per page; -1 means all.", { bindable: true }),
      prop("pageSizes", "array", "Selectable page sizes. Meridian uses [50, 100, 500, -1]."),
    ],
    events: ["onPageChange", "onPageSizeChange"],
    eventDescriptors: [
      event("onPageChange", "value", "Fires with the new 1-based page number."),
      event("onPageSizeChange", "value", "Fires with the new page size (-1 for all)."),
    ],
    hideFromPalette: true,
  },
  {
    type: "Chart",
    component: Chart,
    category: "data",
    acceptsChildren: false,
    defaultProps: {},
    propDescriptors: [
      prop("title", "string"),
      prop("dataSource", "string"),
      prop("chartType", "enum", "Chart visual type.", { values: ["bar", "line", "donut", "area"] }),
      prop("rows", "array"),
      prop("xKey", "string"),
      prop("yKey", "string"),
      prop("series", "array", "Array of { key, label?, color? } series."),
      prop("emptyMessage", "string"),
      prop("totalLabel", "string"),
      prop("height", "number"),
    ],
    hideFromPalette: true,
  },
  {
    type: "KanbanBoard",
    component: KanbanBoard,
    category: "data",
    acceptsChildren: false,
    defaultProps: {},
    propDescriptors: [prop("title", "string"), prop("dataSource", "string"), prop("columns", "array"), prop("rows", "array"), prop("emptyMessage", "string")],
    events: ["onCardClick"],
    eventDescriptors: [event("onCardClick", "card")],
    hideFromPalette: true,
  },
  {
    type: "TreeView",
    component: TreeView,
    category: "data",
    acceptsChildren: false,
    defaultProps: {},
    propDescriptors: [prop("title", "string"), prop("dataSource", "string"), prop("items", "array"), prop("rows", "array"), prop("emptyMessage", "string")],
    events: ["onNodeClick"],
    eventDescriptors: [event("onNodeClick", "node")],
    hideFromPalette: true,
  },
  {
    // Chrome widgets (roadmap step 4): semantic containers only — `<aside>`/`<nav>`/
    // `div[role="toolbar"]` with a sensible default layout, no behavior of their own.
    // Registering here is the whole story — no WidgetPalette code change is needed or
    // made (the palette derives its list from the registry; see notes.md BATASAN TEGAS).
    type: "Sidebar",
    component: Sidebar,
    category: "navigation",
    acceptsChildren: true,
    defaultProps: {},
    propDescriptors: containerProps,
    hideFromPalette: true,
  },
  {
    type: "Navbar",
    component: Navbar,
    category: "navigation",
    acceptsChildren: true,
    defaultProps: {},
    propDescriptors: containerProps,
    hideFromPalette: true,
  },
  {
    type: "Toolbar",
    component: Toolbar,
    category: "navigation",
    acceptsChildren: true,
    defaultProps: {},
    propDescriptors: containerProps,
    hideFromPalette: true,
  },
  {
    // Overlay chrome (roadmap step 5): state-controlled overlays. Documents drive them via
    // props bound to state (`open: { "$bind": "state.overlays.<name>" }`) and forward
    // `onClose` to a setState action — NOT action-triggered like Dialog/Snackbar. Escape,
    // backdrop-click close, and a focus trap live in the components themselves.
    type: "Drawer",
    component: Drawer,
    category: "advanced",
    acceptsChildren: true,
    defaultProps: {},
    propDescriptors: [prop("open", "boolean", "Controls drawer visibility.", { bindable: true }), prop("title", "string"), prop("side", "enum", "Screen edge the drawer slides from.", { values: ["left", "right", "top", "bottom"] }), prop("backdrop", "boolean")],
    events: ["onClose"],
    eventDescriptors: [closeEvent],
    hideFromPalette: true,
  },
  {
    type: "Panel",
    component: Panel,
    category: "advanced",
    acceptsChildren: true,
    defaultProps: {},
    propDescriptors: [prop("open", "boolean", "Controls panel visibility.", { bindable: true }), prop("backdrop", "boolean")],
    events: ["onClose"],
    eventDescriptors: [closeEvent],
    hideFromPalette: true,
  },
  {
    type: "Popover",
    component: Popover,
    category: "navigation",
    acceptsChildren: true,
    defaultProps: {},
    propDescriptors: [
      prop("open", "boolean", "Controlled visibility.", { bindable: true }),
      prop("align", "enum", "Which edge the panel hangs from.", { values: ["start", "end"] }),
      prop("className", "string"),
    ],
    events: ["onClose"],
    eventDescriptors: [closeEvent],
    hideFromPalette: true,
  },
  {
    // Not typically placed directly in a document tree — normally shown via a `showDialog`
    // action (see UIDocumentRenderer, which listens for it). Registered so `type: "Dialog"`
    // is still valid if a document ever wants to control one explicitly via bindings.
    type: "Dialog",
    component: Dialog,
    category: "advanced",
    acceptsChildren: false,
    defaultProps: {},
    propDescriptors: [prop("open", "boolean", "Controls dialog visibility.", { bindable: true }), prop("title", "string"), prop("content", "node")],
    events: ["onClose"],
    eventDescriptors: [closeEvent],
    hideFromPalette: true,
  },
  {
    // Same as Dialog — normally shown via a `showSnackbar` action, registered for explicit use.
    type: "Snackbar",
    component: Snackbar,
    category: "advanced",
    acceptsChildren: false,
    defaultProps: {},
    propDescriptors: [prop("message", "string"), prop("duration", "number"), prop("iconName", "string")],
    events: ["onClose"],
    eventDescriptors: [closeEvent],
    hideFromPalette: true,
  },
  {
    type: "QRCode",
    component: QRCodeSVG,
    category: "base",
    acceptsChildren: false,
    defaultProps: { value: "https://djp.pajak.go.id/faktur" },
    propDescriptors: [prop("value", "string"), prop("size", "number"), prop("fgColor", "string"), prop("bgColor", "string")],
    hideFromPalette: true,
  },
  {
    type: "Barcode",
    component: BarcodeSVG,
    category: "base",
    acceptsChildren: false,
    defaultProps: { value: "1234567890" },
    propDescriptors: [prop("value", "string"), prop("width", "number"), prop("height", "number"), prop("showText", "boolean")],
    hideFromPalette: true,
  },
  {
    type: "DataMatrix",
    component: DataMatrixSVG,
    category: "base",
    acceptsChildren: false,
    defaultProps: { value: "UDI-13485" },
    propDescriptors: [prop("value", "string"), prop("size", "number")],
    hideFromPalette: true,
  },
];
